# Generated by Django 3.1.7 on 2021-03-03 11:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JednorazowaPlatnosc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tytulem', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='KontoBankowe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numer_konta', models.PositiveIntegerField()),
                ('stan_konta', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Leasing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ilosc_rat', models.PositiveIntegerField(null=True)),
                ('data_rozpoczecia', models.DateTimeField(null=True)),
                ('oplata_wstepna', models.PositiveIntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Raty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ilosc_rat', models.PositiveIntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Zakup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('do_zaplaty', models.PositiveIntegerField(null=True)),
                ('tytulem', models.CharField(max_length=200)),
                ('odbiorca', models.CharField(choices=[('Firma', 'Firma'), ('Fizyczna', 'Osoba fizyczna')], max_length=20, null=True)),
                ('sposob_platnosci', models.CharField(choices=[('', 'Podaj formę zapłaty'), ('Gotowka', 'Gotówka'), ('Przelew', 'Przelew'), ('Karta', 'Karta kredytowa')], max_length=50)),
                ('data_zakupu', models.DateTimeField(auto_now_add=True, null=True)),
                ('object_id', models.PositiveIntegerField(null=True)),
                ('content_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('kupujacy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='TreningAPP.kontobankowe')),
            ],
        ),
        migrations.CreateModel(
            name='RataLeasingu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wysokosc_raty', models.PositiveIntegerField()),
                ('data_splaty', models.DateTimeField()),
                ('leasing', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='TreningAPP.leasing')),
            ],
        ),
        migrations.CreateModel(
            name='ProfilUzytkownika',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=100)),
                ('nazwisko', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('data_zalozenia', models.DateTimeField(auto_now_add=True)),
                ('uzytkownik', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PojedynczaRata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wysokosc_raty', models.PositiveIntegerField()),
                ('data_splaty', models.DateTimeField()),
                ('raty', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='TreningAPP.raty')),
            ],
        ),
        migrations.AddField(
            model_name='kontobankowe',
            name='profil_uzytkownika',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TreningAPP.profiluzytkownika'),
        ),
    ]
