# Generated by Django 3.1.7 on 2021-03-03 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TreningAPP', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leasing',
            name='nazwa_firmy',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='leasing',
            name='nip',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
