# Generated by Django 3.1.7 on 2021-03-03 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TreningAPP', '0002_auto_20210303_1208'),
    ]

    operations = [
        migrations.AddField(
            model_name='raty',
            name='imie',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='raty',
            name='nazwisko',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='raty',
            name='pesel',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
