# Generated by Django 3.1.7 on 2021-03-03 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TreningAPP', '0003_auto_20210303_1216'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wydatki',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tytulem', models.CharField(max_length=150)),
                ('wydatek', models.PositiveIntegerField()),
                ('date', models.DateTimeField()),
                ('konto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TreningAPP.kontobankowe')),
            ],
        ),
        migrations.CreateModel(
            name='Wplywy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tytulem', models.CharField(max_length=150)),
                ('wplyw', models.PositiveIntegerField()),
                ('date', models.DateTimeField()),
                ('konto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TreningAPP.kontobankowe')),
            ],
        ),
    ]
